#!/bin/sh
#
# Git pre-commit hook that runs a script to generate 
# Markdown Docs for all Transform based on their YAML File
#
# Will add all files to git staging area as well before the commit
ROOT_DIR=$(git rev-parse --show-toplevel)
export PYTHONPATH=$PYTHONPATH:$ROOT_DIR
echo $PYTHONPATH

echo "Generating Transform Markdown Files from YAML files"
python $ROOT_DIR/docs/docs_generation/doc_generator.py

echo "Adding new Markdown Files to Git Staging Area"
git add *.md
