# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    # Identify invalid files
    - id: check-ast
    - id: check-yaml
    - id: check-json
    # git checks
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: check-case-conflict
    # Python checks
    - id: check-docstring-first
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: name-tests-test
    # General quality checks
    - id: mixed-line-ending
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: 'rasgotransforms/rasgotransforms/transforms|rasgotransforms/rasgotransforms/snippets|^docs'
    - id: check-executables-have-shebangs
    - id: end-of-file-fixer
      exclude: 'rasgotransforms/rasgotransforms/transforms|rasgotransforms/rasgotransforms/snippets|^docs'
    - id: no-commit-to-branch
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120, --skip-string-normalization]
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.10.1
    hooks:
      - id: sqlfmt
        language_version: python

ci:
  autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit.com hooks'
  autofix_prs: true
  autoupdate_branch: 'pre-commit-autoupdate'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: quarterly
