WITH COUNTS AS (
SELECT
  REPLACE('{{ column_name }}','"') AS COLUMN_NAME
  ,COL AS VALUE
  ,COUNT(1) AS VALUE_COUNT
FROM
  (SELECT {{ column_name }} AS COL FROM {{ source_table }})
GROUP BY 2)
SELECT
  COLUMN_NAME
  ,VALUE
  ,VALUE_COUNT
  ,VALUE_COUNT / SUM(VALUE_COUNT) OVER () AS VALUE_FREQUENCY
FROM
  COUNTS
ORDER BY
  VALUE_COUNT desc