WITH COUNTS AS (
SELECT
  REPLACE('{{ COLUMN }}','"') AS FEATURE
  ,COL AS VAL
  ,COUNT(1) AS REC_CT
FROM
  (SELECT {{ COLUMN }}::float AS COL FROM {{ source_table }})
WHERE
  COL IS NOT NULL
GROUP BY 2),
CALCS AS (SELECT MIN(VAL)-1 MIN_VAL, MAX(VAL)+1 MAX_VAL FROM COUNTS),
EDGES AS (SELECT MIN_VAL, MAX_VAL, (MIN_VAL-MAX_VAL) VAL_RANGE, ((MAX_VAL-MIN_VAL)/200) BUCKET_SIZE FROM CALCS),
FREQS AS (
SELECT
  FEATURE
  ,VAL
  ,REC_CT
  ,REC_CT / SUM(REC_CT) OVER () AS FREQ
  ,WIDTH_BUCKET(VAL, MIN_VAL, MAX_VAL, 200) AS HIST_BUCKET
  ,MIN_VAL
  ,MAX_VAL
  ,BUCKET_SIZE
FROM
  COUNTS
CROSS JOIN EDGES)
SELECT
  FEATURE
  ,HIST_BUCKET
  ,MIN_VAL+((HIST_BUCKET-1)*BUCKET_SIZE) AS BUCKET_FLOOR
  ,MIN_VAL+(HIST_BUCKET*BUCKET_SIZE) AS BUCKET_CEILING
  ,MIN(VAL) AS LOW_VAL
  ,MAX(VAL) AS HIGH_VAL
  ,SUM(REC_CT) AS HEIGHT
FROM
  FREQS
GROUP BY 1,2,3,4
order by 2