name: train_test_split
description: Label rows as part of the train or test set based off of percentage split you want to apply to the data
arguments:
  order_by:
    type: column_list
    description: names of column(s) you want order by for the train/test split
  train_percent:
    type: value
    description: Percent of the data you want in the train set, expressed as a decimal (i.e. .8). The rest of the rows will be included in the test set.
example_code: |
    source = rasgo.read.source_data(source_id)
    
    t1 = source.transform(
      transform_name='train_test_split',
      order_by = ['DATE'],
      train_percent = 0.8
    )
    
    t1.preview()