# Publish all Transforms in this Repo to S3
# Run job each time something is pushed/committed to remote 'main' branch
name: Publish Transforms to S3

on:
  push:
    branches:
      - main

jobs:
  publish-accelerators:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: "python:3.7"

    env:
      PYTHONPATH: /__w/RasgoTransforms/RasgoTransforms
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_UPLOAD_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_UPLOAD_SECRET_ACCESS_KEY }}


    steps:
      - uses: actions/checkout@v2

      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Publish Transforms to S3
        run: python python/publish_transforms_to_s3.py

