name: Run RasgoTransforms Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    container:
      image: "python:3.7"

    steps:
      - uses: actions/checkout@v2

      - name: Install RasgoTransforms in Editable Mode and PyTest
        run: |
          python -m pip install --upgrade pip
          pip install -e ./rasgotransforms
          pip install pytest setuptools wheel

      - name: Run Tests
        run: pytest -vv ./rasgotransforms
